# Generated by Django 5.2.6 on 2025-10-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of students', null=True),
        ),
    ]
